version: "3.9"

x-logging:
  &logging
  logging:
    options:
      max-file: '3'
      compress: 'false'
      max-size: '100m'

services:
  mina:
    image: gcr.io/o1labs-192920/mina-daemon:${MINA_BP_VERSION}
    container_name: mina-bp
    environment:
      MINA_PRIVKEY_PASS: ${MINA_PASS}
      UPTIME_PRIVKEY_PASS: ${MINA_PASS}
      MINA_LIBP2P_PASS: ${MINA_PASS}
      RAYON_NUM_THREADS: 6
    command: daemon
       --log-json
       --log-snark-work-gossip true
       --internal-tracing
       --insecure-rest-server
       --log-level Debug
       --file-log-level Debug
       --config-directory /root/.mina-config
       --external-ip ${IP}
       --itn-keys f1F38+W3zLcc45fGZcAf9gsZ7o9Rh3ckqZQw6yOJiS4=,6GmWmMYv5oPwQd2xr6YArmU1YXYCAxQAxKH7aYnBdrk=,ZJDkF9EZlhcAU1jyvP3m9GbkhfYa0yPV+UdAqSamr1Q=,NW2Vis7S5G1B9g2l9cKh3shy9qkI1lvhid38763vZDU=,Cg/8l+JleVH8yNwXkoLawbfLHD93Do4KbttyBS7m9hQ=
       --itn-graphql-port 3089
       --uptime-submitter-key /keys/${WALLET_NAME}
       --uptime-url https://block-producers-uptime-itn.minaprotocol.tools/v1/submit
       --metrics-port 10001
       --enable-peer-exchange true
       --libp2p-keypair /keys/libkey
       --log-precomputed-blocks true
       --max-connections 200
       --peer-list-url https://storage.googleapis.com/seed-lists/testworld-2-0_seeds.txt
       --generate-genesis-proof true
       --block-producer-key /keys/${WALLET_NAME}
       --node-status-url https://nodestats-itn.minaprotocol.tools/submit/stats
       --node-error-url https://nodestats-itn.minaprotocol.tools/submit/stats
       --file-log-rotations 500
    volumes:
      - ./keys:/keys:ro
      - ./.mina-config:/root/.mina-config
    ports:
      - "8302:8302"
      - "3089:3089"
    restart: unless-stopped
    <<: *logging
