version: "3.9"

x-logging:
  &logging
  logging:
    options:
      max-file: '3'
      compress: 'false'
      max-size: '100m'

services:
  mina:
    image: gcr.io/o1labs-192920/mina-daemon:${MINA_VERSION}
    container_name: mina
    env_file: .env
    environment:
      MINA_PRIVKEY_PASS: ${MINA_PASS}
      UPTIME_PRIVKEY_PASS: ${MINA_PASS}
      MINA_LIBP2P_PASS: ${MINA_PASS}
      RAYON_NUM_THREADS: 6
    entrypoint: mina
    command: |
       daemon
       --log-json
       --file-log-level Debug
       --file-log-rotations 500
       --config-directory /root/.mina-config
       --external-ip ${IP}
       --libp2p-keypair /keys/libkey
       --peer-list-url https://storage.googleapis.com/o1labs-gitops-infrastructure/devnet/seed-list-devnet.txt
       --generate-genesis-proof true
       --block-producer-key /keys/${WALLET_NAME}
    volumes:
      - ./keys:/keys:ro
      - ./.mina-config:/root/.mina-config
    ports:
      - "8302:8302"
    restart: unless-stopped
    <<: *logging
